fix(CI): Check out complete history
When determinate/nix-install switched from Determinate Nix 3.21.9 (2.34.8) to
Determinate Nix 3.22.1 (2.35.2) the integration test job started to fail with:

```
error: '/home/runner/work/run-nix-shell/run-nix-shell' is a shallow Git repository, so 'revCount' is not available
```

See https://github.com/NixOS/flake-compat/issues/95